# https://github.com/repository-settings/app

repository:
 #name: .github
  description: null
  homepage: null
  private: true
  has_issues: true
  has_projects: false
  has_downloads: false
  has_wiki: false
  has_pages: false
  has_discussions: false
  archived: false
  is_template: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true
  allow_update_branch: true
  squash_merge_commit_title: "COMMIT_OR_PR_TITLE"
  squash_merge_commit_message: "COMMIT_MESSAGES"
  merge_commit_title: "PR_TITLE"
  merge_commit_message: "PR_BODY"
  allow_forking: true
  web_commit_signoff_required: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: true
  topics: []

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        checks: []
      enforce_admins: false
      required_pull_request_reviews:
        dismissal_restrictions:
          users: []
          teams: []
          apps: []
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        required_approving_review_count: 0
        require_last_push_approval: false
        bypass_pull_request_allowances:
          users: []
          teams: []
          apps: []
      required_linear_history: false
      allow_force_pushes: true
      allow_deletions: true
      block_creations: false
      required_conversation_resolution: true
      lock_branch: false
      allow_fork_syncing: true

labels:
  - name: "bug"
    color: "D73A4A"
    description: "Something isn't working"

  - name: "duplicate"
    color: "CFD3D7"
    description: "This issue or pull request already exists"

  - name: "documentation"
    color: "0052CC"
    description: "Affects or relates to documentation"

  - name: "enhancement"
    color: "A2EEEF"
    description: "New feature or request"

  - name: "good first issue"
    color: "7057FF"
    description: "Good for newcomers"

  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"

  - name: "invalid"
    color: "E4E669"
    description: "This doesn't seem right"

  # Renovate
  - name: "dependencies"
    color: "0366D6"
    description: "Updates one or more dependencies"

  - name: "auto-merge"
    color: "10A631"
    description: "Renovate auto-merges"

  - name: "stop-updating"
    color: "B60205"
    description: "Renovate stops updating"
