# https://github.com/repository-settings/app

repository:
 #name: .github
  description: null
  homepage: null
  topics: null
 #private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: true

labels:
  - name: "bug"
    color: "D73A4A"
    description: "Something isn't working"

  - name: "duplicate"
    color: "CFD3D7"
    description: "This issue or pull request already exists"

  - name: "documentation"
    color: "0052CC"
    description: "Affects or relates to documentation"

  - name: "enhancement"
    color: "A2EEEF"
    description: "New feature or request"

  - name: "good first issue"
    color: "7057FF"
    description: "Good for newcomers"

  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"

  - name: "invalid"
    color: "E4E669"
    description: "This doesn't seem right"

  # Renovate
  - name: "dependencies"
    color: "0366D6"
    description: "Updates one or more dependencies"

  - name: "auto-merge"
    color: "10A631"
    description: "Renovate auto-merges"

  - name: "stop-updating"
    color: "B60205"
    description: "Renovate stops updating"

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts: []
